// Mock API for chat actions with simulated streaming
export const chatApi = {
  sendMessageStream: (chatId, text, model, useKnowledgeBase, onChunk, onDone) => {
    const responseText = `Received prompt: "${text}"

> **Note:** LLM model is not integrated yet. This response is generated by the frontend demo interface using **${model}**.`;

    let sources = null;
    if (useKnowledgeBase) {
      sources = [
        {
          title: "Demo Knowledge Base Source",
          url: "https://example.com/demo-source"
        }
      ];
    }

    // Split text into tokens / words to simulate streaming
    const words = responseText.split(/(\s+)/);
    let index = 0;
    let currentString = "";

    const interval = setInterval(() => {
      if (index < words.length) {
        currentString += words[index];
        onChunk(currentString);
        index++;
      } else {
        clearInterval(interval);
        onDone(currentString, sources);
      }
    }, 15); // Fast streaming simulation
  }
};
